name: "Nix CI"
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - name: Check formatting
        run: nix fmt -- --check .

  build-hosts:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Check NixOS (ix) Evaluation
        run: nix eval .#nixosConfigurations.ix.config.system.build.toplevel.drvPath

      - name: Build NixOS (ix) Toplevel (lite)
        run: nix build .#nixosConfigurations.ix.config.system.build.toplevel --dry-run

      - name: Check Darwin (caladan) Evaluation
        run: nix eval .#darwinConfigurations.caladan.system.drvPath
